### ISSUE TITLE
add graceful shutdown opt

### ISSUE THREAD

**Issue by petar-dambovaliev** [darpi-rs/darpi#12]

**Comment by stappersg** [comment]
What will it bring?   Remote shutdown expliot?


Do know that it is OK to leave those unanswered.. That focus on the actual code is more important.
And explain in the upcoming commit message on the **why**.

**Comment by petar-dambovaliev** [comment]
> What will it bring? Remote shutdown expliot?
> 
> Do know that it is OK to leave those unanswered.. That focus on the actual code is more important.
> And explain in the upcoming commit message on the **why**.

No, this is actually to add a way for you to shutdown the server.

```
let mut app = app!({
        address: "127.0.0.1:3000",
        handlers: [{
            route: "/",
            method: GET,
            handler: my_handler
        }]
    });

    let shutdown = app.shutdown_signal().unwrap();
    shutdown.send(()).unwrap();
```
