### ISSUE TITLE
`gonzales` doesn't match uppercase letter with `ascii_case_insensitive(false)`

### ISSUE THREAD

**Issue by malaire** [darpi-rs/darpi#18]
This test fails with `gonzales = "0.0.2-beta"`

```
use gonzales::RouterBuilder;

fn main() {
    let router = RouterBuilder::new()
        .ascii_case_insensitive(false)
        .build(vec!["/Hello"]);
    let m = router.route("/Hello");
    assert!(m.is_some());
}
```

**Comment by petar-dambovaliev** [comment]
> This test fails with `gonzales = "0.0.2-beta"`
> 
> ```
> use gonzales::RouterBuilder;
> 
> fn main() {
>     let router = RouterBuilder::new()
>         .ascii_case_insensitive(false)
>         .build(vec!["/Hello"]);
>     let m = router.route("/Hello");
>     assert!(m.is_some());
> }
> ```

Thanks, this was fixed in a separate branch and it is merged.

**Comment by stappersg** [comment]
And who will close this issue?
